# Based heavily on:
# http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    #- PYTHON_VERSION: 3.4
    #MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment

  - "pip install pyside pytest pytest-qt pytest-capturelog ThorlabsPM100 pyvisa pyinstaller six"

  - choco install -y InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

# Build is off because it is not applicable to python
build: off

test_script:
  # Run the project tests
     - "python setup.py develop"
     - "py.test tests -s"

after_test:
    
   - "pyinstaller \
      --distpath=scripts/built-dist \
      --workpath=scripts/work-path \
      --noconfirm \
      --clean \
      --icon fastpm100/assets/images/ApplicationIcon.ico \
      --specpath scripts \
      scripts/FastPM100.py"
      
   - "iscc scripts\\Application_InnoSetup.iss"
   - ps: "ls scripts\\built-dist\\*.exe"
   - ps: "ls scripts\\windows_installer\\*.exe"

artifacts:
   - path: scripts\built-dist\FastPM100\*.exe
   - path: scripts\windows_installer\*.exe
   - path: FastPM100.zip
     name: scripts\\built-dist


