# Based heavily on:
# http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    #- PYTHON_VERSION: 3.4
    #MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # First pass at appveyor focused conda
  #- "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  #- activate test-environment
  #
  #- "pip install pyside pytest pytest-qt pytest-capturelog ThorlabsPM100 pyvisa"
  #
  ## no package named packages in 3.1
  #- "pip install pyinstaller==3.0"
  #- "pip install six"

  # no package named pkg_resources
  #- "wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python"
  #- "conda update setuptools"



  # Mimic of development machine miniconda setup
  - conda create --name test-environment python=%PYTHON_VERSION% numpy pyqtgraph pyside

  # On 2016-03-04ish, a build now works with default setuptools -
  # unforutnately, this increase in compatibility manifests as a build
  # error. Something about distribute being the wrong version and/or
  # choco failures
  #- conda remove --name test-environment setuptools
  #- activate test-environment
  # https://github.com/pyinstaller/pyinstaller/issues/1781
  #- "pip install setuptools==19.3"

  - activate test-environment
  - "pip install pyinstaller"
  - "pip install six"
  - "pip install pyvisa"
  - "pip install pytest"
  - "pip install pyserial"
  - "pip install zmq"


  - choco install -y InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

# Build is off because it is not applicable to python
build: off

test_script:
  # Run the project tests
     - "python setup.py develop"
     - "py.test tests -s --appveyor"

after_test:

   - "pyinstaller \
      --distpath=scripts/built-dist \
      --workpath=scripts/work-path \
      --noconfirm \
      --clean \
      --icon fastpm100/assets/images/ApplicationIcon.ico \
      --specpath scripts \
      scripts/FastPM100.py"
      
   - "iscc scripts\\Application_InnoSetup.iss"
   - ps: "ls scripts\\built-dist\\*.exe"
   - ps: "ls scripts\\windows_installer\\*.exe"

   - ps: "7z a FastPM100.zip scripts\\built-dist"

artifacts:
   - path: FastPM100.zip
   - path: scripts\windows_installer\*.exe


